name: e_commerce
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^4.2.1
  intl: ^0.20.2
  firebase_crashlytics: ^5.0.4
  firebase_analytics: ^12.0.4
  flutter_svg: ^2.2.0
  package_info_plus: ^8.3.1
  email_validator: ^3.0.0
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.1.1
  http: ^1.4.0
  get: ^4.7.2
  shared_preferences: ^2.5.3
  logger: ^2.6.1
  flutter_sslcommerz: ^2.5.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/

